import type { WizardConfig } from "./schema";
import { genNft } from "./templates/nft";
import { genMultiToken } from "./templates/multitoken";
import { genWrappedBridge } from "./templates/bridge_wrapped";
import { genAiApp } from "./templates/ai_app";
import { buildManifest } from "./manifest";

export function generate(cfg: WizardConfig) {
  let contract = "";
  if (cfg.contractType === "NFT_L6") contract = genNft(cfg);
  if (cfg.contractType === "MULTITOKEN_L9") contract = genMultiToken(cfg);
  if (cfg.contractType === "WRAPPED_BRIDGE_L13") contract = genWrappedBridge(cfg);
  if (cfg.contractType === "AI_APP_L2_5") contract = genAiApp(cfg);

  const tests = `// ${cfg.contractName} test stub\n\n test \"${cfg.contractName} compiles\" {\n  assert(true)\n }\n`;

  const manifest = buildManifest(cfg);
  const projectToml = `# Lithic project manifest (placeholder)\n[package]\nname = \"${cfg.contractName.toLowerCase()}\"\nversion = \"0.1.0\"\nauthors = [\"KaJ Labs\"]\nlicense = \"Apache-2.0\"\n`;

  return {
    files: {
      [`src/${cfg.contractName}.lithic`]: contract,
      [`tests/${cfg.contractName}.spec.lithic`]: tests,
      "lithic.toml": projectToml,
      "lep100.json": JSON.stringify(manifest, null, 2),
      "README.md": `# ${cfg.contractName}\n\nGenerated by LithicLang.ai LEP100 Contracts Wizard.\n`,
    }
  };
}
