import type { WizardConfig } from "../schema";

export function header() {
  return `// Auto-generated by LithicLang.ai Contracts Wizard
// Target: LithoVM • Language: Lithic (.lithic)
// Credits: Proposed by J. King Kasr • KaJ Labs
`;
}

export function requiresLines(cfg: WizardConfig): string {
  const caps = new Set<string>();
  if (cfg.contractType === "AI_APP_L2_5") caps.add("AI_CALL");
  if (cfg.contractType === "WRAPPED_BRIDGE_L13" || cfg.features.bridgeL13) {
    caps.add("BRIDGE_MINT");
    caps.add("BRIDGE_BURN");
  }
  if (cfg.contractType !== "AI_APP_L2_5") caps.add("TOKEN_TRANSFER");
  if (cfg.features.zkL5) caps.add("ZK_VERIFY");
  if (cfg.features.ppalL14) caps.add("PPAL_CONSUME");
  return Array.from(caps).map((c)=>`requires ${c}`).join("\n");
}

export function addrOrZero(addr?: string) {
  return addr && addr.trim().length ? addr.trim() : "0x0";
}
